version: '3'
services:
  flask:
    build:
      context: .           
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
    restart: always

